// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAmPhiVmXqEDMr4OSy6oUxzmGm2-qnVDs',
    appId: '1:484990867375:android:c4dffaaf162e9a655ac15a',
    messagingSenderId: '484990867375',
    projectId: 'barber-app-944c8',
    storageBucket: 'barber-app-944c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBiltFIcaAXuvkWk5REikynt-Myp6FAhE',
    appId: '1:484990867375:ios:9976e47fa808b4d05ac15a',
    messagingSenderId: '484990867375',
    projectId: 'barber-app-944c8',
    storageBucket: 'barber-app-944c8.firebasestorage.app',
    androidClientId: '484990867375-jbq43i1d1r1e270420vam0ld2hvk4jjo.apps.googleusercontent.com',
    iosClientId: '484990867375-qvdp20m4gviu2bgfuoj5gutsmk77inc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberApp',
  );

}